apps:
  vcrtool:
    command: 'bin/jlip'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/vcrtool/issues'
description: 'Control a JLIP device such as a VCR.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/vcrtool/issues'
license: 'MIT'
name: 'vcrtool'
parts:
  vcrtool:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/vcrtool'
summary: 'Control a JLIP device such as a VCR.'
title: 'vcrtool'
version: '0.0.3'
website: 'https://tatsh.github.io/vcrtool/'
